### ISSUE TITLE
design for "copy" and possible "html"/language indicator

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#1016]
See #1014 re: our meeting discussion

**Comment by tuantinghuang** [comment]
I like the current design! Here's a fine tuned version of it. 

I think the current pink is little too strong that makes the HTML tag pops out from the copy too much, so I switched it to gray and also proposing another option to keep the tag outside of the code block, instead of inside. Attaching both versions here:
Inside
<img width="700" alt="Screenshot 2024-10-07 at 16 53 44" src="https://github.com/user-attachments/assets/3e817c2d-c6eb-4e5a-9314-2d16b7d0cde4">

Outside
<img width="700" alt="Screenshot 2024-10-07 at 16 54 01" src="https://github.com/user-attachments/assets/48cb7b26-6467-488f-a0d2-5cf400b89098">

**Comment by shiffman** [comment]
I have a slight preference for keeping the tab inside the block just for spacing, but it's hard to say without seeing it on the page. All this said, it's only a couple instances in the book so either way works great for me! @tuantinghuang I assume this is fairly trivial in terms of changing the CSS so feel free to go ahead!

**Comment by shiffman** [comment]
I believe this is all set now so closing! Please re-open @tuantinghuang or @jasongao97 if I'm missing something!
