### ISSUE TITLE
5.28 move vehicle

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#195]
The vehicle should move to the same spot as in figure 5.24. And then a dotted line can connect the hypotenuse of the triangle (as seen in 5.25).

![image](https://user-images.githubusercontent.com/191758/213257571-ae04b00f-f02e-4b79-a9e7-f896862e340c.png)

**Comment by zee-em** [comment]
Updated and uploaded to Notion!

**Comment by zee-em** [comment]
Following up-- I am on plane Wi-Fi and it looks like uploads are not completing. Will try again when I'm on the ground.

**Comment by zee-em** [comment]
Complete

**Comment by shiffman** [comment]
Ah! So the vehicle here has to point to the dot at the top of the triangle, it's velocity is not parallel to the dotted line. Rather it's velocity is how the point is chosen (and then the dotted line is connected). see 5.24 for reference

![image](https://user-images.githubusercontent.com/191758/215943444-f6540be8-c14c-420b-81c6-3f0984da824c.png)

**Comment by zee-em** [comment]
I've made this change, and updated in Notion. Do the the vehicle and vector in 5.24 and 5.28 need to match exactly? If so, because of the way the vehicle is positioned in 5.24, if it's in the same location for 5.28 the dotted line crosses through the vehicle. In this latest version of 5.28 it is shifted and rotated slightly. I can send an overlay if that helps visualize it :)   

(btwn the two figures there's more stuff on the right in 5.28 so the positions of everything is a bit different)

**Comment by shiffman** [comment]
No I don't think they need to match exactly! I think the idea is conveyed and each is accurate to itself, I suppose we could move the 5.24 one if we wanted them to, but I don't think it's a big deal. My one quibble is that the arrow (direction of triangle) looks slightly off. This is very much of an obsessive comment but it should point in a way that it passes through the center of the dot. 

I thought maybe this was a case of it being an optical illusion but if I extend the line out it does appear to be a tiny bit off?

![image](https://user-images.githubusercontent.com/191758/217406302-389adb3d-fb38-4e56-9eb6-fd9935b9382e.png)

**Comment by zee-em** [comment]
edited and uploaded to notion :)

**Comment by shiffman** [comment]
👏
