### ISSUE TITLE
WebGL discussion (WebGPU?)

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#332]
(Continuing the discussion with @kfahn22 from https://github.com/CodingTrain/thecodingtrain.com/issues/1113)

I've written a brief section about the WEBGL renderer in [Chapter 4 on Particle Systems](https://nature-of-code-2nd-edition.netlify.app/particles/). @nheidelberger had a great question about whether this might go out of date considering the rapid changing landscape of browser rendering. Does p5.js have any plans to consider a WebGPU renderer for example?

Tagging in @davepagurek in case he has any thoughts? The web version of the book could always be updated of course so the question is really around what to say in the "print" text.

------

Additive blending and particle systems provide an opportunity to discuss renderers in computer graphics. A ***renderer*** is the part of the code that’s responsible for drawing on the screen. The p5.js library's default renderer, which you’ve so far been using without realizing it, is built on top of the standard 2D drawing and animation renderer included in modern web browsers. However, there’s an additional rendering option called `WEBGL`. WebGL, which stands for Web Graphics Library, is a browser-based high-performance renderer for both 2D and 3D graphics. It utilizes additional features available from your computer's graphics card. To enable it, add a third argument to `createCanvas()`.

```javascript
function setup() {
  // Enabling the WEBGL renderer
  createCanvas(640, 240, WEBGL);
}
```

Typically, the WebGL renderer is only necessary if you’re drawing 3D shapes in your p5.js sketch. However, even for 2D sketches, the WebGL renderer can be useful in some cases—depending on your computer's hardware and the specific details of your sketch, it can significantly improve drawing performance. A particle system (especially one with additive blending enabled) is exactly one of these scenarios where many more particles can be drawn without slowing down the sketch in `WEBGL` mode. However,`WEBGL` mode also changes how some functions behave, and it may alter the quality of the rendering itself. Additionally, older devices or browsers may not support the renderer, in which case your sketch won’t work for as wide an audience.

**Comment by davepagurek** [comment]
I think everything in your description sounds correct and won't go out of date!

About WebGPU: I think it's something we'll have to add eventually as browsers invest more in that technology and as third party libraries start to come in that use WebGPU. That said, it probably won't replace WebGL mode, and might be a separate renderer with different capabilities (maybe some GPGPU things for hardware accelerated particle updates?) I think it'll still be a while though, since WebGL isn't being deprecated and supporting a new renderer will take some time.

About other things that might go out of date: while the suggestion in https://github.com/CodingTrain/thecodingtrain.com/issues/1113 of creating a `p5.Geometry` for particles is a good idea for performance, that's an API that we do have plans to change, since currently there's basically no documented API, but it's something we want more people to be able to use. I'm going to hopefully be working out that more user-friendly API soon though, I think it's the next thing on my agenda after 1.7.0 comes out!

**Comment by kfahn22** [comment]
I was actually suggesting else.   I am adding the webgl tutorials to a track, and I was just suggesting that @shiffman  add an explanation on how to use p5.Geometry to create a custom shape.  (Not in the context of particles, but with the supershape or sphere per challenge 25 or 26.).  While the last tutorial discusses custom shapes it uses beginShape, endShape, and vertex.  Also,  I am impressed with how fast the render is using p5.Geometry.

**Comment by davepagurek** [comment]
Ah ok! Agreed, it's something people would probably know how to do because it can help so much with performance, but because it doesn't really have an official API yet, I think probably any tutorial for making custom geometry right now is likely will want to be changed in the near future.

There's some discussion here https://github.com/processing/p5.js/issues/5393 if you're interested in what's in the works! Currently one has to manually create vertices and faces, but we're going to try to make it so that you can build a p5.Geometry out of existing 3d methods in p5.

**Comment by kfahn22** [comment]
I guess I am confused.  Challenge 25 demonstrates how to create a shape using spherical coordinates (although this is a different shape I have recently created):
https://editor.p5js.org/kfahn/sketches/Snumj-AgS
Using p5.Geometry is simpler and the render is much better: https://editor.p5js.org/kfahn/sketches/YceFKpQ8F

**Comment by davepagurek** [comment]
That's definitely the best way to make p5.Geometry right now! I'm only mentioning updates to the API as a heads up for any tutorials that might end up in a print book, which is harder to update. 

To make the learning curve easier when jumping from `beginShape()`/`endShape()` to p5.Geometry, we're going to be updating the API so that you can use the same constructs to initialize geometry, and we plan to add documentation to the p5 site with examples of that. The internal geoemtry API will likely still look the same as what your code there looks like, but one might want printed tutorials to better align with where we see the official docs going long term. That's a choice for authors though, I just wanted to shed some light on what p5's plans are 🙂

**Comment by shiffman** [comment]
Hey all! I think this is a fantastic discussion, but outside the scope of what I'm doing in the book! @davepagurek I'd love to be in touch and maybe do a supplemental video when things are ready in p5.js! Closing for now! (Please tell me if I should re-open or if you have more comments!)

here's the final text and I mention video tutorials so if i make new ones people will find them that way!

![Screen Shot 2023-10-08 at 11 16 23 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/4faf9cad-f49c-444a-8dcd-ff1cb01bced8)

**Comment by davepagurek** [comment]
Looks great @shiffman! The code for creating geometry out of beginShape/vertex/endShape is merged and will be in the next p5 release, I'm happy to talk more about that once it's out if you're interested!

**Comment by shiffman** [comment]
yes please! Nothing would thrill me more than to be done with this book and making new supplementary content! (@davepagurek I've recently learned on twitter that you and I are both fans of the same YouTube channel so this use of the word "content" is quite intentional!)
