### ISSUE TITLE
{.code-wide} markups in Notion

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#353]
The pink box uses `{!1 .code-wide} ` markup in Notion. However, the desired outcome of long line of code should be as the green box, having the comment floating on top of full lines of code:

**PDF screenshot from Chapter 3. Oscillator, after example 3.10:**
<img width="686" alt="Screenshot 2023-07-23 at 4 36 25 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/266e065c-6608-4a20-8d55-2abbbdc5fac2">

**Corresponding Notion section:**
<img width="755" alt="Screenshot 2023-07-23 at 4 40 59 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/bccd796b-c8d3-48af-a762-08cddbf434a1">

**Comment by shiffman** [comment]
The website uses a different methodology for placing the code comments according to the code width. @jasongao97 to look at bringing that over to the PDF to clean up the current way it is rendering. Examples 3.10 is a good one to look at due to the longer line lengths and code comments. Here's what it looks like right now:

<img width="628" alt="Screen Shot 2023-08-02 at 9 36 16 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/e5f46fa8-9e31-4df2-a3f2-09caff9ffc34">

**Comment by jasongao97** [comment]
Here is what is looks like on the website currently.

<img width="549" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/d81278d6-b21c-4ac2-b28a-a5f3306f76ea">

**Comment by shiffman** [comment]
> Here is what is looks like on the website currently.

@jasongao97 ah yes, this looks great! I think if we can match this in the PDF it'll be perfect :)

**Comment by jasongao97** [comment]
This is implemented in #475. Noted the `.code-wide` class is no longer needed since it's using flex box and should automatically detect if it can fit in one line or wrap. Let's check if everything work and can close this issue.

**Comment by shiffman** [comment]
Fantastic! Let me know when #475 is completed and I can double-check everything (and remove "code split" from Notion).

**Comment by shiffman** [comment]
This is working great now. `.code-wide` can be removed from notion, will do that as I see them, but I assume it's not an issue if it's still there by accident. Will open separate individual issues for layout tweaks. Thank you @jasongao97!!
