### ISSUE TITLE
Figure 3.7 - weird formatting on web

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#414]
![image](https://github.com/nature-of-code/noc-book-2023/assets/59444569/231fc619-c8b4-43fb-bff9-5b58beee8d52)

**Comment by shiffman** [comment]
Adding a screenshot of PDF render here, this should look better once #347 is resolved. I can't tell if the image is sitting too low (in the PDF render) due to padding in the image or CSS styling.

The PDF design is high priority now and web is low (as it can be fixed after the book goes into production.)

![Screen Shot 2023-08-27 at 1 51 02 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/1d8297bb-f54b-420e-a0e9-bdb1731333df)

**Comment by shiffman** [comment]
Current PDF: 

<img width="835" alt="Screen Shot 2023-10-08 at 10 33 00 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/5f919554-7250-4ac0-ba72-95ffb56fc651">

Leaving open to be fixed later on the website

**Comment by jasongao97** [comment]
It's fixed! Closing.
