### ISSUE TITLE
Better way of managing of "snippets" continuing or ending w/ text in between.

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#447]
<img width="787" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/aa308936-ed78-4658-b0b7-0cb2a1d9154d">

**Comment by shiffman** [comment]
So this is a symptom of a larger problem that I have yet to figure out the best way to resolve. @wellcaffeinated has brought this up and had a few suggestions. I've been focusing on other things but keep meaning to open an issue to brainstorm a solution then apply across the board. One of the things I do often is start a section of code (like a `class` or even just the `setup()` function and then include short paragraphs of explanation along the way, finishing that snippet later. This is a particularly egregious example where it the end of the `Walker` class is very far away from where I started it (and there's even an "out of context" extra snippet in between.) Some ideas are:

1. inline comments?
```javascript
class Walker() {
  constructor(x) {
    this.x = x;
  }
/* to be continued */
```

2. Maybe I just explain that this is happening in the introduction? (regardless of how I indicate this, I'll want to explain in the introduction.)

3. Some other kind of visual indicator / design element?

```javascript
class Walker() {
  constructor(x) {
    this.x = x;
  }
✂️
```
@tuantinghuang since we are making use of the the openmoji project, maybe we bring in this scissors icon?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/6d17a34b-ef3a-415b-9f2d-af6ba5023858)

I'd welcome any thoughts! (cc @jasongao97 and @nheidelberger)

**Comment by shiffman** [comment]
Just noting that I guess in this case it would look something like:

```javascript

/* snip indicator at the top? */

  step() {
    // 0, 1, 2, or 3
    let choice = floor(random(4));
    //{!9} The random "choice" determines the step.
    if (choice == 0) {
      this.x++;
    } else if (choice == 1) {
      this.x--;
    } else if (choice == 2) {
      this.y++;
    } else {
      this.y--;
    }
  }
}

**Comment by fturmel** [comment]
Right, that makes sense. For what it's worth, my initial reaction to the problem:

For this specific case, would it not be possible to include the whole class at the beginning of this section for reference? That way you don't have to worry about the need to connect all the snippets together to form a working example. I would think that it's valuable for beginners to see the whole example, and not resort only to stitching the fragments in their head. I like the snip icon idea, especially if it could reference the more complete example it was snipped from.

You could also considering numbering the fragments (1 of 3, etc) and add a comment on that last trailing brace to note that it closes the class scope (since it's so far from its opening brace and not contextually relevant to the specific point explained).

**Comment by fturmel** [comment]
A page tear treatment could be nice. Quick mockup (padding isn't right, but you get the idea):

<img width="905" alt="Screenshot 2023-09-09 at 3 29 23 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/a76b0a01-1052-4e3c-a4d1-2ef15cf56ece">

**Comment by wellcaffeinated** [comment]
Ooh. I like the page tear. I suggest emphasizing the torn edges a bit more in the design as the design is functional rather than simply aesthetic. Maybe darker color, or shadow, or something.

I also love the side-by-side with details.. is that new? Or did i just miss that in the notion version?

**Comment by shiffman** [comment]
> I also love the side-by-side with details.. is that new? Or did i just miss that in the notion version?

Sorry I didn't explain this fully @wellcaffeinated! Notion is just a "preview" and place for me to write, there is a build process which generates the website and PDF (you can find the code for this here and in the [fetch-notion](https://github.com/nature-of-code/fetch-notion) submodule.)

You can see the website render here: https://nature-of-code-2nd-edition.netlify.app/ (eventually this will move to natureofcode.com.)

@jasongao97 @tuantinghuang and I are prioritizing the PDF build right now since that is what has a firm deadline. If you want to see how that is looking, I can share that with you over email!

I also like this tear idea! We're still finalizing the code block design for the PDF and can share some updates here as we get further. If we go with a new design element like this, we'll have to invent some markup for Notion that we can parse during the "fetch notion" process and reformat for the PDF + web.

**Comment by shiffman** [comment]
Adding this image for reference as another spot where any new design element could be applied. Blue lines are start and end of a block I am explaining. Pink are the "to be continued" and "picking up from before" spots. This is from Notion not the website or PDF render.

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/e2f7e53a-8c1b-4420-98fc-224d5393b5ad)

**Comment by shiffman** [comment]
Circling back to this. @tuantinghuang tried a few design options and we actually liked just a simple `...`. Here's a sample:

<img width="664" alt="Screen Shot 2023-09-18 at 12 41 31 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/23552c6d-b6c3-494e-ac1b-cd2245edfe2a">

I've started adding in the ellipses in a few places in the book. One spot that we could try experimenting with ways to render it is in Koch curve section of Chapter 8. Where I write the full `kochPoints()` function broken up with short explanations. I suppose the indentation of the `...` should match where the code leaves off? @jasongao97 is this something you think it makes sense to parse then add in or just should we just literally include the `...`?

<img width="581" alt="Screen Shot 2023-09-18 at 12 43 27 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/c7c6f7de-0ebf-4cce-b968-3d5e5f3e170f">

**Comment by nheidelberger** [comment]
Sorry I'm just weighing in on this now. Simple is great! FYI, at No Starch we typically use --snip-- for this purpose (with two hyphens on each side, and "snip" italicized), but dots also seem fine. Might just want to say something about it explicitly in the Introduction. Or I think there's a passage in Chapter 0 or 1 that talks about this?

**Comment by shiffman** [comment]
For anyone following, here is the current design we are looking at! I'm thinking that I may not use scissors in places where it is very obvious the code is continued with just a short paragraph in between (like on the top left of this page).

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/6e547861-052b-4264-824d-d55b8ead8ffe)

**Comment by fturmel** [comment]
I like the scissors and dotted lines.

Personally, I find it tricky to scan the page and get a sense of what is code and what is explanatory text because there are no bounding boxes around the snippets. If I'm the only one bothered by this, please ignore!

Some ideas (apologies for the sloppy alignments, margins, etc):

**A)** Gray bounding box, vertical bar separates code and comment. The height of the bar indicates the lines commented upon without surrounding them.

![image](https://github.com/nature-of-code/noc-book-2023/assets/4009209/f5f60838-1ade-46c1-b49a-59c73d0ab832)

**B)** Flip the snippet colors: bounding box is gray, and the highlighted lines are white / cut-outs and leave margins so we still get a sense of the bounding box.

![image](https://github.com/nature-of-code/noc-book-2023/assets/4009209/c99f7f9b-f912-4535-8a4d-b40278870602)

**Comment by shiffman** [comment]
Thank you @fturmel, I really appreciate all of your thoughtful and helpful feedback! I'm down to the wire here so having to make some tough choices and just finalize things for the book. We've tried so many different ways  for the code snippets, many similar to your suggestions. . but a lot of them result in the pages being too noisy and not working well for print. I'll tag in @tuantinghuang for any last considerations, but we are likely to land where we have settled!

**Comment by shiffman** [comment]
We are trying a few more ideas that are close to some of @fturmel's suggestions! Follow along in #530, thanks @tuantinghuang!!

**Comment by shiffman** [comment]
This is a screenshot of how it looks in the introduction and we are going to be applying this now throughout the text! TBD whether we want to include something similar on the website.

![Screen Shot 2023-10-20 at 2 46 35 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/fd772f0b-555b-4d7c-9d48-e6453b19c802)

**Comment by shiffman** [comment]
This is all set! @jasongao97 @tuantinghuang I'm going to close out this issue, but we can open a new one / revisit later if we want to consider adding a design element on the website.
