### ISSUE TITLE
Comments in code blocks that overflow will start scrolled to the right

### ISSUE THREAD

**Issue by supercrafter100** [nature-of-code/noc-book-2#646]
I'm not sure if this is a thing my browser is doing but testing it out on mobile view, when a comment overflows the screen width and thus get's a scrollbar. It always starts scrolled to the right. This is quite annoying because you'd expect it to start from the left when reading it. See the following gif: https://gyazo.com/af06f725b2cf16a55488378e1a8b6b03

**Comment by dipamsen** [comment]
Can confirm, container is scrolled to right on page load. 
Looks like this is only the case in case of a commented block, normal long blocks of code without comments are scrolled to the start, which kind of makes sense, because in the large screen layout, the comment is rendered on the right.

![image](https://github.com/nature-of-code/noc-book-2023/assets/59444569/2cb95004-83fd-41ee-935b-f417118fc6f8)

**Comment by jasongao97** [comment]
Thank you for reporting this! It should be fixed now.
