### ISSUE TITLE
Code Comment bug?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#786]
This particular code comment was only paired with the first two lines rather than with the full `add()` function. I've resolved it by manually adding `{!4}` but noting it here as an FYI.

Notion:
<img width="786" alt="Screen Shot 2024-02-24 at 10 04 35 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/32dbffb9-b4fb-4c01-89c5-c7f9bbea3bd8">

PDF:
![Screen Shot 2024-02-24 at 10 04 40 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/350909c1-159a-4cbb-a2bf-848a68bca9f8)

**Comment by jasongao97** [comment]
```html
<strong>add(v) {
    this.x = this.x + v.x;
</strong><strong>    this.y = this.y + v.y;
</strong><strong>  }</strong>
    this.y = this.y + v.y;
  }</strong>
```

It appears that the `<strong>` tag was messing up the recognition of indented block. Since there isn't simple build-process fix currently, I'd recommend to mark annotations(bold, italic, etc) either:

- On the whole block
- or only on text (without the indented whitespace)

which I have updated in Notion.

**Comment by shiffman** [comment]
I will double check and close.

**Comment by shiffman** [comment]
All set!
