### ISSUE TITLE
web-only in build process

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#916]
We have a `pdf-only` in the build process for things like #780 it would be nice to have a `web-only` Notion page.

**Comment by jasongao97** [comment]
Since `magicbook` recognize files by their name & path, I am thinking of two ways of implementing this:

1. **Annotated folder**: the `web-only` HTML files will be stored in a special folder with name like `content/web/` or `content/web-only/`.
2. **Annotated file**: name the `web-only` HTML as `[slug].web-only.html` instead of `[slug].html`

Is either better? @shiffman

**Comment by shiffman** [comment]
I'm not sure I completely understand, does this affect the navigation on the website or is just for the repo's purposes? For the repos purposes either is fine! Probably 2?

**Comment by shiffman** [comment]
Let's just for the future, configure `magicbook.json` file to select things to include or not include in the PDF. All Notion pages will be "PDF-only", "Published", or "Draft"
