### ISSUE TITLE
Social Sharing Preview Image + Title

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#938]
When a link is shared, each page should include a preview image and the title. Right now, the homepage, for example, has no preview (should use the book mock-up) and the title "Examples":

<img width="1102" alt="Screen Shot 2024-04-20 at 10 05 50 AM" src="https://github.com/nature-of-code/noc-book-2/assets/191758/390b8f6a-45bb-4c1f-9270-32c9cc49cb19">

See https://thecodingtrain.com for an example system.

**Comment by jasongao97** [comment]
I added the description of the first 150 characters for each chapter. Would it be preferable for the preview images to be the same as the opening figures for the chapters, or should they all simply feature the book mock-up?

**Comment by shiffman** [comment]
I think either the physical book mock-up or a nice example screenshot? Don't feel strongly about this, but I think the chapter opening images will be confusing as the primary shared element.

**Comment by jasongao97** [comment]
> I think either the physical book mock-up or a nice example screenshot? Don't feel strongly about this, but I think the chapter opening images will be confusing as the primary shared element.

Got it, that makes sense! I'll start with the mock-up first and then explore if there are any better options.

**Comment by shiffman** [comment]
Re-opening, looks like the social sharing image doesn't work on twitter?

https://twitter.com/pierre_nel/status/1785347109987762275

<img width="601" alt="Screen Shot 2024-04-30 at 7 45 04 PM" src="https://github.com/nature-of-code/noc-book-2/assets/191758/2ee6c4b7-32d8-43b3-bba2-3e2ca6d60e5d">

It is working in Discord though maybe I should write a short few sentences for each chapter for text to include?

<img width="633" alt="Screen Shot 2024-04-30 at 7 46 45 PM" src="https://github.com/nature-of-code/noc-book-2/assets/191758/01f9cbaa-664d-4085-ad73-3226a38c04c4">

**Comment by fturmel** [comment]
Hi team, saw the Coding Train issue linking back here.

At first glance, it could be because the `twitter:image` meta tag is a relative link instead of absolute? Sometimes these service features can be proxied/cached and it's possible that they wouldn't find the origin anymore.

![CleanShot 2024-05-28 at 11 22 02@2x](https://github.com/nature-of-code/noc-book-2/assets/4009209/d31c5eaa-dd4e-4907-bf74-729c25440fb4)


Google around for tools that can help audit og/twitter metadata, that might be helpful.
https://socialsharepreview.com/?url=https://natureofcode.com/
https://www.opengraph.xyz/url/https%3A%2F%2Fnatureofcode.com%2F

**Comment by fturmel** [comment]
Also it looks like the "name" attribute should be used for Twitter and not "property". Open Graph uses "property" so it seems OK.

https://developer.x.com/en/docs/twitter-for-websites/cards/overview/summary
https://ogp.me/

It might've looked like some of the tags worked because there are fallbacks to og tags in some cases. https://developer.x.com/en/docs/twitter-for-websites/cards/overview/markup

**Comment by fturmel** [comment]
@shiffman with #975 merged this issue can be closed. The previously mentioned tweet displays the thumbnail image correctly now.

**Comment by shiffman** [comment]
Thank you!
